
const KEY="ttcShiftRecordsV1"; let editingId=null; const $=id=>document.getElementById(id);
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function today(){const d=new Date(),o=d.getTimezoneOffset(),l=new Date(d.getTime()-o*60000);return l.toISOString().slice(0,10)}
function hmMin(v){const m=String(v||"").match(/^(\d{1,3}):([0-5]\d)$/);return m?+m[1]*60 + +m[2]:0}
function minHm(n){return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function reset(){editingId=null;$("shiftForm").reset();$("date").value=today();$("camera").value="Unknown";$("incident").value="None";document.querySelector("#shiftForm .primary").textContent="Save Shift";$("saveMessage").textContent=""}
$("shiftForm").addEventListener("submit",e=>{e.preventDefault();const r={id:editingId||uid(),date:$("date").value,routes:$("routes").value.trim(),crew:$("crew").value.trim(),run:$("run").value.trim(),bus:$("bus").value.trim(),start:$("start").value,finish:$("finish").value,paid:$("paid").value.trim(),ot:$("ot").value.trim(),camera:$("camera").value,incident:$("incident").value,notes:$("notes").value.trim(),updatedAt:new Date().toISOString()};let a=load(),i=a.findIndex(x=>x.id===r.id);if(i>=0)a[i]=r;else a.push(r);save(a);$("saveMessage").textContent=editingId?"Shift updated.":"Shift saved.";renderAll();setTimeout(reset,700)})
$("clearForm").onclick=reset;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");renderAll()});
$("search").oninput=renderHistory;
function renderHistory(){const q=$("search").value.trim().toLowerCase(),list=$("historyList");list.innerHTML="";const a=load().sort((x,y)=>(y.date||"").localeCompare(x.date||"")).filter(r=>!q||Object.values(r).some(v=>String(v).toLowerCase().includes(q)));if(!a.length){list.innerHTML='<div class="record-card">No matching records.</div>';return}a.forEach(r=>{const el=$("cardTemplate").content.firstElementChild.cloneNode(true);el.querySelector(".card-date").textContent=r.date||"";el.querySelector(".card-route").textContent=`Route(s): ${r.routes||""}`;el.querySelector(".card-grid").innerHTML=`<div><b>Crew:</b> ${esc(r.crew)}</div><div><b>Run:</b> ${esc(r.run)}</div><div><b>Bus:</b> ${esc(r.bus)}</div><div><b>Camera:</b> ${esc(r.camera)}</div><div><b>Start:</b> ${esc(r.start)}</div><div><b>Finish:</b> ${esc(r.finish)}</div><div><b>Paid:</b> ${esc(r.paid)}</div><div><b>OT:</b> ${esc(r.ot)}</div><div><b>Incident:</b> ${esc(r.incident)}</div>`;el.querySelector(".card-notes").textContent=r.notes||"";el.querySelector(".edit-btn").onclick=()=>edit(r.id);el.querySelector(".delete-btn").onclick=()=>del(r.id);list.appendChild(el)})}
function edit(id){const r=load().find(x=>x.id===id);if(!r)return;editingId=id;["date","routes","crew","run","bus","start","finish","paid","ot","camera","incident","notes"].forEach(k=>$(k).value=r[k]??"");document.querySelector("#shiftForm .primary").textContent="Update Shift";document.querySelector('[data-tab="new"]').click();window.scrollTo({top:0,behavior:"smooth"})}
function del(id){if(confirm("Delete this shift record?")){save(load().filter(x=>x.id!==id));renderAll()}}
function counts(a){const m=new Map();a.forEach(x=>m.set(x,(m.get(x)||0)+1));return [...m.entries()].sort((x,y)=>y[1]-x[1]).slice(0,8)}
function top(id,a){$(id).innerHTML=a.length?a.map(([k,v])=>`<div class="rank-row"><span>${esc(k)}</span><strong>${v}</strong></div>`).join(""):"No records yet."}
function renderSummary(){const a=load();$("sumShifts").textContent=a.length;$("sumPaid").textContent=minHm(a.reduce((s,r)=>s+hmMin(r.paid),0));$("sumOT").textContent=minHm(a.reduce((s,r)=>s+hmMin(r.ot),0));$("sumIncidents").textContent=a.filter(r=>r.incident&&r.incident!=="None").length;let routes=[];a.forEach(r=>String(r.routes||"").split(/[\/,]+/).map(x=>x.trim()).filter(Boolean).forEach(x=>routes.push(x)));$("sumRoutes").textContent=new Set(routes).size;$("sumBuses").textContent=new Set(a.map(r=>r.bus).filter(Boolean)).size;top("topRoutes",counts(routes));top("topBuses",counts(a.map(r=>r.bus).filter(Boolean)))}
function download(content,name,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$("exportCsv").onclick=()=>{const a=load(),h=["Date","Route(s)","Crew","Run","Bus","Start","Finish","Paid","OT","Side Camera","Incident","Notes"],rows=a.map(r=>[r.date,r.routes,r.crew,r.run,r.bus,r.start,r.finish,r.paid,r.ot,r.camera,r.incident,r.notes]);download([h,...rows].map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),"TTC_Shift_Log.csv","text/csv;charset=utf-8")}
$("exportJson").onclick=()=>download(JSON.stringify(load(),null,2),"TTC_Shift_Log_Backup.json","application/json");
$("importJson").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d))throw 0;if(confirm(`Restore ${d.length} records? This replaces current records.`)){save(d);renderAll();alert("Backup restored.")}}catch{alert("Could not read backup file.")}e.target.value=""}
$("deleteAll").onclick=()=>{if(confirm("Delete ALL TTC records from this device?")){localStorage.removeItem(KEY);renderAll()}}
function renderAll(){renderHistory();renderSummary()}
reset();renderAll();
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}
